# Generated by Django 6.0.4 on 2026-04-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255, unique=True, verbose_name='IG Post ID')),
                ('caption_raw', models.TextField()),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
    ]
